name: download
channels:
  - conda-forge
dependencies:
  - python >=3.11
  - numpy>=1.17
  - netcdf4<=1.6.1
  - xarray>=2023.4.0
  - dask>=2023.4.0
  - pathlib
  - pandas
  - zarr>=3
  - copernicusmarine
